include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'build/**'
    - '**/*.g.dart'
    - '**/firebase_options.dart'

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_print: true
    avoid_double_and_int_checks: true
    avoid_empty_else: true
    avoid_final_parameters: true
    avoid_unnecessary_containers: true
    avoid_void_async: true
    await_only_futures: true
    cancel_subscriptions: true
    file_names: true
    no_duplicate_case_values: true
    no_self_assignments: true
    noop_primitive_operations: true
    package_names: true
    prefer_adjacent_string_concatenation: true
    prefer_contains: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_null_aware_method_calls: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true
    use_build_context_synchronously: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    
