name: stutor_workspace
description: Stutor workspace
version: 0.0.1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  melos: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^6.4.1
  flutter_lints: ^3.0.1
  husky: ^0.1.6

flutter:

 
