name: flutter_shared
description: "A Flutter repo of shared components and other things."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  auto_route: ^8.1.3
  collection: ^1.18.0
  connectivity_plus: ^5.0.0
  copy_with_extension: ^5.0.2
  dart_ipify: ^1.1.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1
  http: ^1.1.0
  js: ^0.6.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  logger: ^2.0.2+1
  package_info_plus: ^4.2.0
  path: ^1.8.2
  permission_handler: ^11.3.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.1
  shared_preferences_android: ^2.2.1
  shared_preferences_foundation: ^2.3.5
  string_similarity: ^2.0.0
  url_launcher: ^6.1.10
  uuid: ^4.3.3
  wakelock_plus: ^1.1.3
  new_version_plus: ^0.0.11
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^6.4.1
  auto_route_generator: ^8.0.0
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  copy_with_extension_gen: ^5.0.2
  riverpod_generator: ^2.3.11
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
