targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/views/**_view.dart
      auto_route_generator:auto_router_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/routing/app_router.dart
      copy_with_extension_gen:copy_with_extension_gen:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/models/**.dart
      freezed:
        generate_for:
          - lib/models/**.dart
      json_serializable:
        generate_for:
          - lib/models/**.dart
      riverpod_generator:riverpod_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/providers/**.dart
      
